# Generated by Django 5.1.1 on 2025-09-19 04:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('capacidad', models.PositiveSmallIntegerField(default=1)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('teleconsulta', 'Teleconsulta')], default='presencial', max_length=20)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agenda (bloque)',
                'verbose_name_plural': 'Agendas (bloques)',
                'db_table': 'agendas',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'db_table': 'especialidades',
            },
        ),
        migrations.CreateModel(
            name='EstadoCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Estado de cita',
                'verbose_name_plural': 'Estados de cita',
                'db_table': 'estados_cita',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(max_length=120)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=190, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('comuna', models.CharField(blank=True, max_length=120, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'pacientes',
                'indexes': [models.Index(fields=['email'], name='pacientes_email_26e212_idx'), models.Index(fields=['apellido'], name='pacientes_apellid_e130e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='core.agenda')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_creadas', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='core.estadocita')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='core.paciente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'citas',
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=190, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profesionales', to='core.especialidad')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_profesional', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profesional',
                'verbose_name_plural': 'Profesionales',
                'db_table': 'profesionales',
            },
        ),
        migrations.AddField(
            model_name='agenda',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendas', to='core.profesional'),
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('comuna', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'ubicaciones',
                'constraints': [models.UniqueConstraint(fields=('nombre',), name='uk_ubicacion_nombre')],
            },
        ),
        migrations.AddField(
            model_name='agenda',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendas', to='core.ubicacion'),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='core.role')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rol de usuario',
                'verbose_name_plural': 'Roles de usuario',
                'db_table': 'usuario_rol',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('actualizar', 'Actualizar'), ('cambiar_estado', 'Cambiar estado'), ('cancelar', 'Cancelar'), ('reprogramar', 'Reprogramar')], max_length=20)),
                ('detalle', models.JSONField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_citas', to=settings.AUTH_USER_MODEL)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoria', to='core.cita')),
            ],
            options={
                'verbose_name': 'Auditoría de cita',
                'verbose_name_plural': 'Auditoría de citas',
                'db_table': 'auditoria_citas',
                'indexes': [models.Index(fields=['cita'], name='auditoria_c_cita_id_a04a3f_idx'), models.Index(fields=['usuario'], name='auditoria_c_usuario_0a4fc7_idx'), models.Index(fields=['creado_en'], name='auditoria_c_creado__05bfce_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactoCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('llamada', 'Llamada'), ('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('otro', 'Otro')], max_length=12)),
                ('resultado', models.CharField(choices=[('exitoso', 'Exitoso'), ('sin_respuesta', 'Sin respuesta'), ('buzon', 'Buzón/Contestador'), ('numero_invalido', 'Número inválido'), ('rechazado', 'Rechazado'), ('reagendar', 'Solicita reagendar'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('contacto_con', models.CharField(choices=[('paciente', 'Paciente'), ('familiar', 'Familiar'), ('tutor', 'Tutor'), ('otro', 'Otro')], default='paciente', max_length=12)),
                ('fecha_contacto', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='core.cita')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contactos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contacto de cita',
                'verbose_name_plural': 'Contactos de cita',
                'db_table': 'contactos_cita',
                'indexes': [models.Index(fields=['cita', 'fecha_contacto'], name='contactos_c_cita_id_2f4114_idx'), models.Index(fields=['usuario'], name='contactos_c_usuario_49bebf_idx'), models.Index(fields=['canal'], name='contactos_c_canal_d29dab_idx'), models.Index(fields=['resultado'], name='contactos_c_resulta_46d1f4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['paciente'], name='citas_pacient_3cb46f_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['estado'], name='citas_estado__36145e_idx'),
        ),
        migrations.AddIndex(
            model_name='profesional',
            index=models.Index(fields=['apellido'], name='profesional_apellid_00c784_idx'),
        ),
        migrations.AddIndex(
            model_name='profesional',
            index=models.Index(fields=['especialidad'], name='profesional_especia_c7bcb1_idx'),
        ),
        migrations.AddIndex(
            model_name='agenda',
            index=models.Index(fields=['inicio'], name='agendas_inicio_cce5c1_idx'),
        ),
        migrations.AddIndex(
            model_name='agenda',
            index=models.Index(fields=['profesional', 'inicio', 'fin'], name='agendas_profesi_f6cd3b_idx'),
        ),
        migrations.AddConstraint(
            model_name='agenda',
            constraint=models.UniqueConstraint(fields=('profesional', 'inicio', 'fin'), name='uk_agenda_prof_inicio_fin'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('usuario', 'rol')},
        ),
    ]
