# Generated by Django 5.1.1 on 2025-09-19 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cita',
            name='citas_estado__36145e_idx',
        ),
        migrations.RemoveIndex(
            model_name='contactocita',
            name='contactos_c_cita_id_2f4114_idx',
        ),
        migrations.RemoveIndex(
            model_name='contactocita',
            name='contactos_c_usuario_49bebf_idx',
        ),
        migrations.RemoveIndex(
            model_name='contactocita',
            name='contactos_c_canal_d29dab_idx',
        ),
        migrations.RemoveIndex(
            model_name='contactocita',
            name='contactos_c_resulta_46d1f4_idx',
        ),
        migrations.RemoveIndex(
            model_name='profesional',
            name='profesional_apellid_00c784_idx',
        ),
        migrations.RemoveIndex(
            model_name='profesional',
            name='profesional_especia_c7bcb1_idx',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='direccion',
        ),
        migrations.AlterField(
            model_name='cita',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='core.agenda'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='core.paciente'),
        ),
        migrations.AlterField(
            model_name='contactocita',
            name='canal',
            field=models.CharField(choices=[('llamada', 'Llamada'), ('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contactocita',
            name='contacto_con',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='contactocita',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactocita',
            name='fecha_contacto',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contactocita',
            name='resultado',
            field=models.CharField(choices=[('confirmado', 'Confirmado'), ('rechazado', 'Rechazado'), ('sin_respuesta', 'Sin respuesta'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contactocita',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='nombre',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['agenda', 'estado'], name='citas_agenda__d719ff_idx'),
        ),
        migrations.AddIndex(
            model_name='contactocita',
            index=models.Index(fields=['cita'], name='contactos_c_cita_id_7cc2e6_idx'),
        ),
        migrations.AddIndex(
            model_name='contactocita',
            index=models.Index(fields=['fecha_contacto'], name='contactos_c_fecha_c_61c95f_idx'),
        ),
    ]
