# Generated by Django 5.1.1 on 2025-10-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
    ]
