# Generated by Django 4.2.1 on 2025-09-22 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_passwordresetcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetCode',
        ),
    ]
