# Generated by Django 5.1.1 on 2025-09-24 02:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_passwordresetcode'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paciente',
            name='pacientes_email_26e212_idx',
        ),
        migrations.RemoveIndex(
            model_name='paciente',
            name='pacientes_apellid_e130e6_idx',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='apellido',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='nombre',
            new_name='nombres',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='paciente',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='paciente',
            name='debe_cambiar_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='password',
            field=models.CharField(default='hola', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['rut'], name='core_pacien_rut_8abb8c_idx'),
        ),
        migrations.AlterModelTable(
            name='paciente',
            table=None,
        ),
    ]
