# Generated by Django 5.1.1 on 2025-10-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_paciente_direccion_paciente_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
